<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-3 mb-3">
  <a class="navbar-brand" href="#">Student Flow</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse  navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="index.php">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="contact_admin.php">Contact Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="manage_modules.php">Manage Modules</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="manage_users.php">Manage Users</a>
      </li>
      
    </ul>
  </div>
</nav>